### ISSUE TITLE
Plugins require version that's not available

### ISSUE THREAD

**Issue by matthewdias** [lad1337/XDM#193]
A few plugins say they can't be installed because I'm not up to date, but the updater says there aren't any updates. 
<img width="113" alt="screenshot 2015-08-09 20 56 30" src="https://cloud.githubusercontent.com/assets/3302524/9158279/4fdb23a8-3ed9-11e5-897b-a54ad0e3817d.png">

**Comment by KaraokeStu** [comment]
I'm also having the same issue, which is stopping me from installing any plugins that I need

**Comment by lad1337** [comment]
how did you install it ? What platform ?
Would you be able to install it via git?

**Comment by KaraokeStu** [comment]
Hi, I've installed it from my synology, which then gets the latest version from GIT and updates itself.

However, I've noticed there is no 0.5.19.0 in your releases list?

**Comment by lad1337** [comment]
Okay probably because it uses the master ... Develop does have the version ... I'll try to merge this weekend

**Comment by matthewdias** [comment]
Does the mac version pull updates from git as well? That's what I have installed.

**Comment by lad1337** [comment]
Nope ... I have to create another build for that ... What is the build number you use ?

**Comment by matthewdias** [comment]
0.5.18.109

**Comment by lad1337** [comment]
okay i merged develop with master and now there is a 0.5.19
but i could not create an app looks like py2app is broken on el captain https://forums.developer.apple.com/thread/6987

**Comment by lad1337** [comment]
okay try https://github.com/lad1337/XDM/releases/download/0.5.19/XDM.app.zip

**Comment by matthewdias** [comment]
Not sure if I'm doing something wrong but after launching the app, the server doesn't seem to be running.

**Comment by Therealkam** [comment]
Ok the problem you may have is that the process was still open / the port was occupied

```
  INFO : Starting the XDM http web server
  ERROR : Unable to start web server, is something else running on port 8085?
```

have a look who is running on 8085 and find its PID ( i.e. 70008)

```
$> lsof -n -i4TCP:8085 | grep LISTEN
$< username   70008   0.0  0.5  2564448  22032   ??  S     2:17PM   0:10.26 /Applications/XDM.app/Contents/MacOS/XDM -psn_0_7563062
```

And kill it without mercy :D 

```
kill -9 70008
```

**Comment by matthewdias** [comment]
Alright I'm moving right now so I'll try that once I settle in and get my server back up

**Comment by matthewdias** [comment]
So finally got around to it. Nothing's running on 8085. Even XDM after starting the app.
